
/// C54: user-selected cue-holding figures. The same 100-unit paths supply the Figma SVGs.
private struct BTPlayerViewGlyph: View {
    enum Pose { case standing, aiming }
    let pose: Pose
    var body: some View {
        Canvas { context, size in
            var path = Path()
            switch pose {
                case .standing:
                path.addEllipse(in: CGRect(x: 31, y: 6, width: 16, height: 16))
                path.move(to: CGPoint(x: 28, y: 37))
                path.addLine(to: CGPoint(x: 26, y: 61))
                path.addQuadCurve(to: CGPoint(x: 21, y: 65), control: CGPoint(x: 25, y: 67))
                path.addQuadCurve(to: CGPoint(x: 20, y: 58), control: CGPoint(x: 19, y: 64))
                path.addLine(to: CGPoint(x: 24, y: 35))
                path.addQuadCurve(to: CGPoint(x: 32, y: 29), control: CGPoint(x: 25, y: 29))
                path.addLine(to: CGPoint(x: 46, y: 29))
                path.addQuadCurve(to: CGPoint(x: 54, y: 36), control: CGPoint(x: 53, y: 29))
                path.addLine(to: CGPoint(x: 56, y: 45))
                path.addLine(to: CGPoint(x: 66, y: 49))
                path.addQuadCurve(to: CGPoint(x: 69, y: 55), control: CGPoint(x: 71, y: 51))
                path.addQuadCurve(to: CGPoint(x: 64, y: 56), control: CGPoint(x: 68, y: 58))
                path.addLine(to: CGPoint(x: 52, y: 52))
                path.addLine(to: CGPoint(x: 49, y: 41))
                path.addLine(to: CGPoint(x: 50, y: 86))
                path.addLine(to: CGPoint(x: 56, y: 90))
                path.addQuadCurve(to: CGPoint(x: 54, y: 94), control: CGPoint(x: 59, y: 93))
                path.addLine(to: CGPoint(x: 45, y: 94))
                path.addLine(to: CGPoint(x: 39, y: 63))
                path.addLine(to: CGPoint(x: 34, y: 94))
                path.addLine(to: CGPoint(x: 24, y: 94))
                path.addQuadCurve(to: CGPoint(x: 24, y: 90), control: CGPoint(x: 20, y: 93))
                path.addLine(to: CGPoint(x: 29, y: 86))
                path.addLine(to: CGPoint(x: 30, y: 40))
                path.move(to: CGPoint(x: 68, y: 26))
                path.addLine(to: CGPoint(x: 68, y: 49))
                path.move(to: CGPoint(x: 68, y: 57))
                path.addLine(to: CGPoint(x: 68, y: 94))
                case .aiming:
                path.addEllipse(in: CGRect(x: 41.5, y: 24.5, width: 13.0, height: 13.0))
                path.move(to: CGPoint(x: 6, y: 43))
                path.addLine(to: CGPoint(x: 94, y: 43))
                path.move(to: CGPoint(x: 25, y: 43))
                path.addQuadCurve(to: CGPoint(x: 29, y: 47), control: CGPoint(x: 25, y: 45))
                path.addQuadCurve(to: CGPoint(x: 44, y: 47), control: CGPoint(x: 39, y: 49))
                path.addLine(to: CGPoint(x: 52, y: 43))
                path.move(to: CGPoint(x: 43, y: 39))
                path.addLine(to: CGPoint(x: 77, y: 25))
                path.addQuadCurve(to: CGPoint(x: 84, y: 29), control: CGPoint(x: 82, y: 23))
                path.addLine(to: CGPoint(x: 90, y: 42))
                path.addQuadCurve(to: CGPoint(x: 88, y: 47), control: CGPoint(x: 92, y: 46))
                path.addQuadCurve(to: CGPoint(x: 83, y: 43), control: CGPoint(x: 83, y: 49))
                path.addLine(to: CGPoint(x: 77, y: 33))
                path.addLine(to: CGPoint(x: 68, y: 39))
                path.addLine(to: CGPoint(x: 76, y: 46))
                path.move(to: CGPoint(x: 56, y: 43))
                path.addLine(to: CGPoint(x: 65, y: 49))
                path.addQuadCurve(to: CGPoint(x: 65, y: 53), control: CGPoint(x: 67, y: 50))
                path.addLine(to: CGPoint(x: 59, y: 61))
                path.addQuadCurve(to: CGPoint(x: 57, y: 68), control: CGPoint(x: 57, y: 64))
                path.addLine(to: CGPoint(x: 56, y: 76))
                path.addLine(to: CGPoint(x: 50, y: 79))
                path.addQuadCurve(to: CGPoint(x: 51, y: 82), control: CGPoint(x: 47, y: 82))
                path.addLine(to: CGPoint(x: 61, y: 82))
                path.addLine(to: CGPoint(x: 62, y: 72))
                path.addQuadCurve(to: CGPoint(x: 66, y: 64), control: CGPoint(x: 62, y: 67))
                path.addLine(to: CGPoint(x: 72, y: 59))
                path.addQuadCurve(to: CGPoint(x: 77, y: 52), control: CGPoint(x: 76, y: 56))
                path.move(to: CGPoint(x: 84, y: 47))
                path.addLine(to: CGPoint(x: 88, y: 64))
                path.addLine(to: CGPoint(x: 94, y: 79))
                path.addQuadCurve(to: CGPoint(x: 92, y: 82), control: CGPoint(x: 96, y: 82))
                path.addLine(to: CGPoint(x: 85, y: 82))
                path.addQuadCurve(to: CGPoint(x: 85, y: 79), control: CGPoint(x: 82, y: 82))
                path.addLine(to: CGPoint(x: 89, y: 77))
                path.addLine(to: CGPoint(x: 78, y: 59))
            }
            let t = CGAffineTransform(scaleX: size.width / 100, y: size.height / 100)
            context.stroke(path.applying(t), with: .color(HUDStyle.valueMeasured),
                           style: StrokeStyle(lineWidth: size.width * 0.055, lineCap: .round, lineJoin: .round))
        }
        // Optical centering: the cue is asymmetric, while the person's body is the anchor.
        .offset(x: pose == .standing ? 2 : -2)
        .accessibilityHidden(true)
    }
}
